Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-admin-user-config
  AttributeDefinitions:
    -
      AttributeName: adminUserId
      AttributeType: S
    -
      AttributeName: configName
      AttributeType: S
  KeySchema:
    -
      AttributeName: adminUserId
      KeyType: HASH
    -
      AttributeName: configName
      KeyType: RANGE
  BillingMode: PAY_PER_REQUEST
  #ProvisionedThroughput:
  #  ReadCapacityUnits: 1
  #  WriteCapacityUnits: 5
