Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-file
  AttributeDefinitions:
    -
      AttributeName: fileId
      AttributeType: S
    -
      AttributeName: fileStatus
      AttributeType: S
    -
      AttributeName: createdAt
      AttributeType: S
  KeySchema:
    -
      AttributeName: fileId
      KeyType: HASH
  #ProvisionedThroughput:
  #  ReadCapacityUnits: 5
  #  WriteCapacityUnits: 3
  BillingMode: PAY_PER_REQUEST
  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    -
      IndexName: fileStatusCreatedAtGsi
      KeySchema:
      -
        AttributeName: fileStatus
        KeyType: HASH
      -
        AttributeName: createdAt
        KeyType: RANGE
      Projection:
        NonKeyAttributes:
          - fileId
          - fileType
          - serviceId
          - mimeType
        ProjectionType: INCLUDE
