Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-post
  AttributeDefinitions:
    -
      AttributeName: postId
      AttributeType: S
    -
      AttributeName: serviceIdSlug
      AttributeType: S
    -
      AttributeName: serviceId
      AttributeType: S
    -
      AttributeName: statusPublishAt
      AttributeType: S
    -
      AttributeName: createdAt
      AttributeType: S
    -
      AttributeName: publishAt
      AttributeType: S
  KeySchema:
    -
      AttributeName: postId
      KeyType: HASH
  #ProvisionedThroughput:
  #  ReadCapacityUnits: 5
  #  WriteCapacityUnits: 3
  BillingMode: PAY_PER_REQUEST

  GlobalSecondaryIndexes:
    -
      IndexName: serviceIdSlugGsi
      KeySchema:
      -
        AttributeName: serviceIdSlug
        KeyType: HASH
      Projection:
        ProjectionType: ALL
      #ProvisionedThroughput:
      #  ReadCapacityUnits: 5
      #  WriteCapacityUnits: 3
    -
      IndexName: statusPublishAtGsi
      KeySchema:
      -
        AttributeName: serviceId
        KeyType: HASH
      -
        AttributeName: statusPublishAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
      #ProvisionedThroughput:
      #  ReadCapacityUnits: 5
      #  WriteCapacityUnits: 3
    -
      IndexName: createdAtGsi
      KeySchema:
      -
        AttributeName: serviceId
        KeyType: HASH
      -
        AttributeName: createdAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
      #ProvisionedThroughput:
      #  ReadCapacityUnits: 5
      #  WriteCapacityUnits: 3
    -
      IndexName: publishAtGsi
      KeySchema:
      -
        AttributeName: serviceId
        KeyType: HASH
      -
        AttributeName: publishAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
      #ProvisionedThroughput:
      #  ReadCapacityUnits: 5
      #  WriteCapacityUnits: 3
