Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-vote-count
  AttributeDefinitions:
    -
      AttributeName: serviceId
      AttributeType: S
    -
      AttributeName: contentId
      AttributeType: S
    -
      AttributeName: contentIdType
      AttributeType: S
  KeySchema:
    -
      AttributeName: serviceId
      KeyType: HASH
    -
      AttributeName: contentIdType
      KeyType: RANGE
  #ProvisionedThroughput:
  #  ReadCapacityUnits: 8
  #  WriteCapacityUnits: 8
  BillingMode: PAY_PER_REQUEST
  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  LocalSecondaryIndexes:
    -
      IndexName: ServiceIdContentIdLsi
      KeySchema:
      -
        AttributeName: serviceId
        KeyType: HASH
      -
        AttributeName: contentId
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
