service: content-api
defaultRegion: 'ap-northeast-1'

sesRegion: 'ap-northeast-1'
contactSubject: 'Inquiries accepted'
contactTypes: '[{"val":"1","label":"About this site"},{"val":"2","label":"About defects"},{"val":"3","label":"Others"}]'
contactEmailFrom: 'info@example.com'
contactEmailFromName: 'Sample'
contactEmailCompanyName: 'Sample.co'
contactEmailCompanySiteUrl: 'http://example.com'
