service: content-api
awsAccountId: 'Your-AWS-Acconnt-ID'
defaultRegion: 'ap-northeast-1'
sesRegion: 'us-west-2'
cognitoJwtHeaderName: 'Authorization'
cognitoJwtHeaderPrefix: 'Bearer'

mediaAcceptMimeTypes: '{"image":["image/png","image/gif","image/jpeg"],"file":["image/png","image/gif","image/jpeg","application/pdf"]}'
mediaImageSizes: '["1200x1200","800x800","400x400","400x400xs"]'

commentImporterColumnConversionTable: '{"hoge": {"Created Time":"createdAt", "Comment":"body", "Handle Name":"profiles:nickname", "Ages":"profiles:age", "Comment ID":"localId", "Browser":"ua", "IP Address":"ip", "Unpublish Flag":"unpublish"}}'
commentImporterContentList: '{"hoge": [{"id":"content001", "label":"Content1"}, {"id":"content002", "label":"Content2"}]}'
