domainName: your-project-api-dev.example.com
corsAcceptOrigins: ''
notificationEmail: admin-dev@example.com
logsRestApiAccessLogging: true # Optional configuration which enables or disables access logging. Defaults to true.
logsRestApiExecutionLogging: true # Optional configuration which enables or disables execution logging. Defaults to true.
logsRestApiLevel: INFO # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
logsRestApiFullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.
debugLogEnabled: true

appMemorySize: 128 # MB

mediaS3BucketName: "media-dev.example.com"
mediaImageMakerMemorySize: 256 # MB
mediaImageMakerTimeout: 600 # s
mediaImageMakerFileSizeLimit: 5 # MB

commentDefaultPublishStatus: "unpublish"
commentImportTimeout: 300 # s
commentImportMemorySize: 256 # MB
commentImportS3BucketName: "your-content-resources"
commentImportS3BucketPath: "your-project/dev/comments"
commentImportS3BucketSizeLimit: 3 # MB
commentImportCsvRowsCountLimit: 1000 # Stop execution to import comments from csv, if run over this value
commentImporterNoticeEmails: '{"hoge": {"to":"admin@example.com", "from":"admin@example.com", "from_name":"System Administrator"}}'

# For Admin Console
cognitoRegion: 'us-east-1'
cognitoUserpoolId: 'us-east-1_*********'
cognitoAppClientId: '**************************'
cognitoCheckTokenExpiration: True # If set Falsae, disable token expiration checking for testing purposes
