domainName: content-api.example.com
corsAcceptOrigins: 'https://prod.example.com,https://stg.example.com'
notificationEmail: admin@example.com
logsRestApiAccessLogging: false # Optional configuration which enables or disables access logging. Defaults to true.
logsRestApiExecutionLogging: false # Optional configuration which enables or disables execution logging. Defaults to true.
logsRestApiLevel: ERROR # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
logsRestApiFullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.
acceptServiceIds: "hoge,fuga"

acceptTypes: "like,dislike"
appMemorySize: 256

commentDefaultPublishStatus: "unpublish"

backupVoteLogThresholdDaysOlderThan: 14 # Days
backupVoteLogCountForAll: 1000
backupVoteLogCountForEachService: 500
backupVoteLogMemorySize: 516
backupVoteLogEventSchedule: rate(7 days)

# For Admin Console
cognitoRegion: 'ap-northeast-1'
cognitoUserpoolId: 'ap-northeast-1_*********'
cognitoAppClientId: '**************************'
cognitoCheckTokenExpiration: True # If set Falsae, disable token expiration checking for testing purposes
