Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-contact
  AttributeDefinitions:
    -
      AttributeName: serviceId
      AttributeType: S
    -
      AttributeName: updatedAt
      AttributeType: S
    -
      AttributeName: serviceIdCode
      AttributeType: S
  KeySchema:
    -
      AttributeName: serviceIdCode
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.contact.billingMode}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.contact.provisionedThroughput.readCapacityUnits}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.contact.provisionedThroughput.writeCapacityUnits}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    -
      IndexName: ${self:custom.prjPrefix}-contact-list-gsi
      KeySchema:
      -
        AttributeName: serviceId
        KeyType: HASH
      -
        AttributeName: updatedAt
        KeyType: RANGE
      Projection:
        NonKeyAttributes:
          - code
          - status
          - subject
        ProjectionType: INCLUDE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 3
