- Effect: Allow
  Action:
    - dynamodb:DescribeTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:BatchGetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
  Resource: arn:aws:dynamodb:*:*:table/*
- Effect: Allow
  Action:
    - logs:CreateLogGroup
    - logs:CreateLogStream
    - logs:PutLogEvents
  Resource:
    - '*'
#- Effect: 'Allow'
#  Action:
#    - 'dynamodb:*'
#  Resource: arn:aws:dynamodb:*:*:table/*
- Effect: Allow
  Action:
    - s3:ListBucket
    - s3:GetObject
    - s3:PutObject
    - s3:DeleteObject
  Resource: arn:aws:s3:::${self:custom.s3BucketName}/*
- Effect: Allow
  Action:
    - ses:SendEmail
    - ses:SendRawEmail
  Resource: '*'
- Effect: Allow
  Action:
    - cognito-idp:ListUsers
    - cognito-idp:AdminGetUser
    - cognito-idp:AdminCreateUser
    - cognito-idp:AdminUpdateUserAttributes
    - cognito-idp:AddCustomAttributes
    - cognito-idp:AdminDeleteUser
    - cognito-idp:AdminDeleteUserAttributes
  Resource: arn:aws:cognito-idp:${self:custom.cognitoRegion}:${self:custom.awsAccontId}:userpool/${self:custom.cognitoUserpoolId}
